name: br
description: Representation and validation of brazilian document numbers and other related stuff
version: 1.0.0
homepage: https://github.com/base4sistemas/br

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0-0
  test: ^1.16.0
